# Generated by Django 4.1 on 2023-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/film-photos/'),
        ),
    ]
