# Generated by Django 4.2.1 on 2023-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_film_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_link',
            field=models.URLField(null=True, verbose_name='Youtube link'),
        ),
    ]
